name: S3 Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@main

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region us-east-1 \
            --acl public-read \
            dist/frontend s3://metaradar.io

      #- name: Deploy Cloudfront
      #  env:
      #    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ID }}
      #    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      #  run: aws cloudfront create-invalidation --distribution-id E278T2AO4LEM6J --paths "/*" --region us-east-1


